# Generated by Django 3.2 on 2021-04-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210409_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Обслуживание'), ('o', 'В долг'), ('a', 'Доступна'), ('r', 'Зарезервированна')], default='m', help_text='Наличие книги', max_length=1, verbose_name='Статус'),
        ),
    ]
